{
 "title": "Pizza Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_attempts_success_total[1m]) * 60",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_attempts_failed_total[1m]) * 60",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "service_latency_milliseconds", "legendFormat": "Request latency" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "active_users{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencymBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_millibitcoin_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_percent{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    { "expr": "system_cpu_usage_percent", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total[1m]) * 60",
     "legendFormat": "Pizza purchases"
    },
    { "expr": "pizza_creation_failures_total", "legendFormat": "Purchase failures" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m]) * 60",
     "legendFormat": "Total HTTP Requests"
    },
    {
     "expr": "rate(http_requests_get_total[1m]) * 60",
     "legendFormat": "GET Requests"
    },
    {
     "expr": "rate(http_requests_put_total[1m]) * 60",
     "legendFormat": "PUT Requests"
    },
    {
     "expr": "rate(http_requests_post_total[1m]) * 60",
     "legendFormat": "POST Requests"
    },
    {
     "expr": "rate(http_requests_delete_total[1m]) * 60",
     "legendFormat": "DELETE Requests"
    }
   ]
  }
 ]
}